In [5]:
pd.read_sql("SELECT COUNT(*) FROM customer_predictions", engine)

   count
0   7043

In [4]:
results.to_sql('customer_predictions', engine, if_exists='replace', index=False)

43

In [3]:
results = pd.DataFrame({
    'customerID': df['customerID'],
    'churn_probability': churn_probs,
    'predicted_ltv': predicted_ltvs,
    'actual_churn': df['Churn']
})
results.head()

   customerID  churn_probability  predicted_ltv  actual_churn
0  7590-VHVEG           0.564172        29.9610             0
1  5575-GNVDE           0.005742      2029.9955             0
2  3668-QPYBK           0.687258       247.4735             1
3  7795-CFOCW           0.015668      1784.9550             0
4  9237-HQITU           0.783856       241.9750             1

In [2]:
churn_input = df.reindex(columns=churn_features, fill_value=0)
churn_probs = churn_model.predict_proba(churn_input)[:, 1]

ltv_input = df.reindex(columns=ltv_features, fill_value=0)
predicted_ltvs = ltv_model.predict(ltv_input)

In [1]:
import pandas as pd
import joblib
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:root123@localhost:5432/telco_churn")

customerID = pd.read_sql("SELECT * FROM customers", engine)['customerID']
df = pd.read_sql("SELECT * FROM customers_model_ready", engine)
df.insert(0, 'customerID', customerID)

churn_model = joblib.load("churn_model.pkl")
churn_features = joblib.load("churn_features.pkl")
ltv_model = joblib.load("ltv_model.pkl")
ltv_features = joblib.load("ltv_features.pkl")